### ISSUE TITLE
Can't start

### ISSUE THREAD

**Issue by avenue2013** [bfwg/angular-spring-starter#50]
Always get this
Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "5.0.2".
Error: Version of @angular/compiler-cli needs to be 2.3.1 or greater. Current version is "5.0.2".
    at Object.<anonymous> (/Users/avenuezhang/ngproject/angular-spring-starter/frontend/node_modules/@ngtools/webpack/src/index.js:27:11)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/avenuezhang/ngproject/angular-spring-starter/frontend/node_modules/@angular/cli/tasks/eject.js:10:19)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)

npm ERR! Darwin 17.3.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! angular-spring-starter-ui@0.1.1 start: `ng serve --proxy-config proxy.conf.json`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the angular-spring-starter-ui@0.1.1 start script 'ng serve --proxy-config proxy.conf.json'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the angular-spring-starter-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ng serve --proxy-config proxy.conf.json
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs angular-spring-starter-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls angular-spring-starter-ui
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/avenuezhang/ngproject/angular-spring-starter/frontend/npm-debug.log

**Comment by bfwg** [comment]
Hi @avenue2013 , can you try again as I have made some changes.
